---
kind: pipeline
type: docker
name: default

platform:
  arch: amd64
  os: linux

environment:
  GOPROXY: https://mirrors.aliyun.com/goproxy/,direct
  GO111MODULE: on

steps:
- name: build
  image: golang:1.23-alpine
  commands:
  - env
  - sh scripts/build.sh

- name: publish
  image: kit101z/dockerbuildkit:1
  settings:
    auto_tag: true
    dockerfile: ./Dockerfile
    repo: kit101z/drone-ext-env
    platform: linux/amd64,linux/arm64
    username:
      from_secret: docker_registry_username_docker.io
    password:
      from_secret: docker_registry_password_docker.io
  when:
    event:
    - push
    - tag